FROM php:8.2-cli

# Extensiones necesarias para Laravel + PostgreSQL
RUN apt-get update && apt-get install -y \
    libpq-dev \
    unzip \
    git \
    curl \
    libzip-dev \
    zip \
    && docker-php-ext-install pdo pdo_pgsql

# Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

# Servir Laravel en dev
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
