services:
 
  vue:
    image: node:20
    container_name: vue_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./node_modules:/var/www/html/node_modules
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    command: npm run dev -- --host 0.0.0.0
